// Frontend mirror of the backend toolRegistry — drives ToolsHub cards and
// ToolInputForm field generation. Keep endpoint + fields in sync with
// apps/server/src/modules/tools/toolRegistry.js.

export const tools = [
  {
    id: "etsy-title-generator",
    slug: "etsy-seo-title-generator",
    endpoint: "title-generator",
    name: "Etsy SEO Title Generator",
    icon: "Type",
    category: "SEO",
    description: "Turn a product idea into 5 keyword-rich, high-converting Etsy titles.",
    creditCost: 1,
    fields: [
      { name: "productType", label: "Product type", type: "text", required: true, placeholder: "e.g. handmade ceramic mug" },
      { name: "keywords", label: "Target keywords", type: "text", placeholder: "e.g. minimalist, gift for her" },
      { name: "materials", label: "Materials", type: "text", placeholder: "e.g. stoneware clay" },
      { name: "style", label: "Style / aesthetic", type: "text", placeholder: "e.g. boho, cottagecore" },
    ],
  },
  {
    id: "etsy-tag-generator",
    slug: "etsy-tag-generator",
    endpoint: "tag-generator",
    name: "Etsy Tag Generator",
    icon: "Tags",
    category: "SEO",
    description: "Generate exactly 13 SEO-optimized tags, each under 20 characters.",
    creditCost: 1,
    fields: [
      { name: "productType", label: "Product type", type: "text", required: true, placeholder: "e.g. leather crossbody bag" },
      { name: "keywords", label: "Target keywords", type: "text", placeholder: "e.g. personalized, boho" },
      { name: "audience", label: "Target audience", type: "text", placeholder: "e.g. young professionals" },
    ],
  },
  {
    id: "etsy-description-generator",
    slug: "etsy-description-generator",
    endpoint: "description-generator",
    name: "Etsy Description Generator",
    icon: "FileText",
    category: "SEO",
    description: "A scroll-stopping hook, keyword-rich body, and clear call to action.",
    creditCost: 1,
    fields: [
      { name: "productType", label: "Product type", type: "text", required: true },
      { name: "keywords", label: "Keywords to include", type: "text" },
      { name: "materials", label: "Materials", type: "text" },
      { name: "features", label: "Key features", type: "textarea", placeholder: "One per line" },
      { name: "tone", label: "Tone", type: "select", options: ["warm and friendly", "playful", "luxury", "minimal and direct"] },
    ],
  },
  {
    id: "etsy-keyword-generator",
    slug: "etsy-keyword-generator",
    endpoint: "keyword-generator",
    name: "Etsy Keyword Generator",
    icon: "Search",
    category: "Keywords",
    description: "Short-tail, long-tail, and seasonal buyer search phrases.",
    creditCost: 1,
    fields: [
      { name: "productType", label: "Product type", type: "text", required: true },
      { name: "niche", label: "Niche", type: "text" },
      { name: "audience", label: "Audience", type: "text" },
    ],
  },
  {
    id: "etsy-listing-analyzer",
    slug: "etsy-listing-analyzer",
    endpoint: "listing-analyzer",
    name: "Etsy Listing Analyzer",
    icon: "ScanSearch",
    category: "Optimization",
    description: "Paste an existing listing and get a scored audit with fixes.",
    creditCost: 2,
    fields: [
      { name: "title", label: "Current title", type: "text", required: true },
      { name: "description", label: "Current description", type: "textarea" },
      { name: "tags", label: "Current tags (comma-separated)", type: "text" },
      { name: "price", label: "Current price", type: "text" },
    ],
  },
  {
    id: "etsy-pricing-calculator",
    slug: "etsy-pricing-calculator",
    endpoint: "pricing-calculator",
    name: "Etsy Pricing Calculator",
    icon: "Calculator",
    category: "Pricing",
    description: "Instant, free — suggests a retail price for your target margin.",
    creditCost: 0,
    fields: [
      { name: "materialCost", label: "Material cost ($)", type: "number", required: true },
      { name: "laborHours", label: "Labor hours", type: "number", required: true },
      { name: "hourlyRate", label: "Hourly rate ($)", type: "number", defaultValue: 15 },
      { name: "overheadCost", label: "Overhead cost ($)", type: "number", defaultValue: 0 },
      { name: "desiredProfitMarginPercent", label: "Desired profit margin (%)", type: "number", defaultValue: 30 },
    ],
  },
  {
    id: "etsy-fee-calculator",
    slug: "etsy-fee-calculator",
    endpoint: "fee-calculator",
    name: "Etsy Fee Calculator",
    icon: "Receipt",
    category: "Pricing",
    description: "Instant, free — breaks down Etsy's fees to show your real take-home.",
    creditCost: 0,
    fields: [
      { name: "salePrice", label: "Sale price ($)", type: "number", required: true },
      { name: "shippingPrice", label: "Shipping price ($)", type: "number", defaultValue: 0 },
      { name: "quantity", label: "Quantity", type: "number", defaultValue: 1 },
      { name: "hasOfferOrEtsyAds", label: "Using Etsy Ads?", type: "checkbox" },
      { name: "isOffsiteAds", label: "Sold via Offsite Ads?", type: "checkbox" },
    ],
  },
  {
    id: "etsy-shop-name-generator",
    slug: "etsy-shop-name-generator",
    endpoint: "shop-name-generator",
    name: "Etsy Shop Name Generator",
    icon: "Store",
    category: "Branding",
    description: "10 memorable, space-free shop name ideas ready for Etsy.",
    creditCost: 1,
    fields: [
      { name: "niche", label: "Niche", type: "text", required: true },
      { name: "style", label: "Style / vibe", type: "text" },
      { name: "keywords", label: "Inspiration keywords", type: "text" },
    ],
  },
  {
    id: "etsy-product-idea-generator",
    slug: "etsy-product-idea-generator",
    endpoint: "product-idea-generator",
    name: "Etsy Product Idea Generator",
    icon: "Lightbulb",
    category: "Research",
    description: "8 low-competition product ideas matched to your skills and budget.",
    creditCost: 2,
    fields: [
      { name: "niche", label: "Niche", type: "text", required: true },
      { name: "skills", label: "Your skills / equipment", type: "text" },
      { name: "budget", label: "Budget level", type: "select", options: ["low", "medium", "high"] },
    ],
  },
  {
    id: "holiday-keyword-finder",
    slug: "holiday-keyword-finder",
    endpoint: "holiday-keyword-finder",
    name: "Holiday Keyword Finder",
    icon: "CalendarHeart",
    category: "Keywords",
    description: "Match your niche to upcoming holidays with real buyer search phrases.",
    creditCost: 1,
    fields: [
      { name: "niche", label: "Niche", type: "text", required: true },
      { name: "upcomingHolidayWindow", label: "Time window", type: "select", options: ["next 3 months", "next 6 months", "next 12 months"] },
    ],
  },
  {
    id: "etsy-trend-explorer",
    slug: "etsy-trend-explorer",
    endpoint: "trend-explorer",
    name: "Etsy Trend Explorer",
    icon: "TrendingUp",
    category: "Research",
    description: "Directional trend insights — rising styles, colors, and watchouts.",
    creditCost: 2,
    fields: [{ name: "niche", label: "Niche", type: "text", required: true }],
  },
];

export const getToolBySlug = (slug) => tools.find((t) => t.slug === slug);
export const toolCategories = [...new Set(tools.map((t) => t.category))];
