import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowRight, Sparkles } from "lucide-react";
import Button from "../ui/Button.jsx";

export default function HeroSection() {
  return (
    <section className="relative overflow-hidden bg-forge-glow">
      <div className="mx-auto max-w-6xl px-6 pt-20 pb-24 text-center">
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="inline-flex items-center gap-2 rounded-full border border-forge-border bg-forge-surface px-4 py-1.5 mb-8"
        >
          <Sparkles size={14} className="text-emerald-400" />
          <span className="text-xs font-mono uppercase tracking-wide text-ink-300">11 AI tools, one toolkit</span>
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="font-display text-4xl sm:text-6xl font-semibold leading-[1.05] max-w-4xl mx-auto"
        >
          Forge Etsy listings that <span className="text-emerald-400">actually sell.</span>
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="mt-6 text-lg text-ink-300 max-w-2xl mx-auto"
        >
          Titles, tags, descriptions, pricing, and trend research — generated by AI,
          tuned for Etsy's search algorithm, ready in seconds.
        </motion.p>

        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4"
        >
          <Button as={Link} to="/signup" className="px-8 py-3.5">
            Start free — no card needed <ArrowRight size={16} />
          </Button>
          <Button as={Link} to="/tools" variant="secondary" className="px-8 py-3.5">
            Explore all tools
          </Button>
        </motion.div>
      </div>
    </section>
  );
}
